# Generated by Django 5.1.1 on 2024-09-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='image',
            field=models.ImageField(upload_to='subastas_imagen/'),
        ),
    ]
