# Generated by Django 5.1.1 on 2024-11-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_puja'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='estado',
            field=models.CharField(default='Activa', max_length=20),
        ),
    ]
